name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
        if: matrix.os == 'ubuntu-latest'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: rm -rf /tmp/*
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
      - name: Build with Maven (Windows)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: mvn -ntp -U verify
        shell: cmd
        if: matrix.os == 'windows-latest'
      - name: Build with Maven (not Windows)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          sudo -E mvn -ntp -U verify
          sudo chown -R runner target
        if: matrix.os != 'windows-latest'
